- name: installation
  pacman: name={{item}}
  with_items:
    - nodm
    - i3-wm
    - i3status
    - xf86-input-evdev
    - xorg-server
    - xf86-video-fbdev
    - numlockx
    - dunst

- name: directory structure
  file: path={{item}} owner=mpd group=mpd state=directory
  with_items:
    - /home/mpd/.config
    - /home/mpd/.config/i3

- name: configuration
  copy: src={{item}} dest=/{{item}} owner=mpd group=mpd
  with_items:
    - home/mpd/.xinitrc
    - home/mpd/.config/i3/config
    - home/mpd/.config/i3/autostart

- name: set executable
  file: path={{item}} mode=0755 owner=mpd group=mpd
  with_items:
    - /home/mpd/.xinitrc
    - /home/mpd/.config/i3/autostart

- name: setup nodm to launch mpd session
  file: src=etc/nodm.conf dest=/etc/nodm.conf mode=0755 owner=root group=root
  notify : systemctl restart nodm

- name: activation
  service: name=nodm enabled=yes

# TODO
# dunst configuration

