- name: wpa_supplicant configuration
  include: wpa_supplicant.yml

- name: creates wlan configurations
  copy: src=etc/systemd/network/wireless.network dest=/etc/systemd/network/wireless.network owner=root group=root mode=644
#  notify: network restart

