- name: installation
  pacman: name={{item}} state=present
  with_items:
    - wpa_supplicant

# following point aim at the use of specific driver for my particular wifi card
- name: wpa_supplicant service custom configuration
  lineinfile: dest=/usr/lib/systemd/system/wpa_supplicant@.service regexp='^(ExecStart=.* -i%I)$' line='\1 -Dwext' backrefs=yes
  register: wpa_modif

- name: daemon reload
  shell: systemctl daemon-reload
  when: wpa_modif|changed

- name: variables verification
  fail: msg="ansible should have been launched whith option -e 'wifiSsid=xxx wifiPass=xxx'"
  when: wifiSsid is not defined or wifiPass is not defined

- name: wpa_supplicant.conf creation
  shell: wpa_passphrase {{wifiSsid}} {{wifiPass}} | grep -v "#psk" > /etc/wpa_supplicant/wpa_supplicant.conf

- name: wpa_supplicant device configuration file permissions
  file: path=/etc/wpa_supplicant/wpa_supplicant.conf owner=root group=root mode=600

- name: wpa_supplicant device configuration file
  file: src=/etc/wpa_supplicant/wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant-{{item}}.conf owner=root group=root mode=644 state=link
  with_items: ansible_interfaces
  when: item | match('wl.*')

- name: service enable
  service: name=wpa_supplicant@{{item}}.service state=started enabled=yes
  with_items: ansible_interfaces
  when: item | match('wl.*')

