- name: installation
  pacman: name={{item}} state=present
  with_items:
    - mesa-libgl # sounds bad to me but dependencies...
    - libx264
    - mpd
    - mpc

- name: group
  group: name=mpd state=present

- name: user
  user: name=mpd group=mpd groups=audio,sudo createhome=yes shell=/bin/bash

- name: set up mpd user xorg environment
  include: xorg.yml

- name: music directory
  file: path=/srv/music state=directory owner=mpd group=mpd mode=755

- name: configuration
  template: src=etc/mpd.conf dest=/etc/mpd.conf owner=root group=root mode=644
  notify: systemctl restart user mpd

- name: pulseaudio service
  #service: name=pulseaudio enabled=yes arguments="--user"
  shell: systemctl --user enable pulseaudio
  become: mpd

- name: service
  #service: name=mpd enabled=yes arguments="--user"
  shell: systemctl --user enable mpd
  become: mpd

- name: working dir tree
  file: path=/var/lib/mpd owner=mpd group=mpd mode=755 state=directory
  with_items:
    - /var/lib/mpd
    - /var/lib/mpd/playlists
