#!/bin/bash

# returns OK if argument matches in ps list
runProc() {
  return $(ps auxw | grep $1 | grep -v grep | wc -l)
}

logFile=/dev/null

>${logFile}

# X global env
xhost +localhost >>${logFile} 2>&1
setxkbmap -layout fr-latin9 >>${logFile} 2>&1
numlockx >>${logFile} 2>&1

# daemons
runProc "dunst" && nohup dunst >>${logFile} 2>&1 </dev/null &

